Show upgrade success/error message.

diff --git a/tomato64/board/x86_64/overlay/sbin/upgrade b/tomato64/board/x86_64/overlay/sbin/upgrade
--- a/tomato64/board/x86_64/overlay/sbin/upgrade
+++ b/tomato64/board/x86_64/overlay/sbin/upgrade
@@ -1,3 +1,11 @@
 #!/bin/sh
 
 tar -I "zstd -f" -xf $1 -C /
+
+result=$?
+
+if [ "$result" -eq 0 ]; then
+	printf "image successfully flashed\n"
+else
+	printf 'error code "%d" returned' "$result"
+fi
