Create fs_mount_ro nvram variable to make the root filesystem read-only.

diff --git a/tomato64/board/x86_64/overlay/sbin/upgrade b/tomato64/board/x86_64/overlay/sbin/upgrade
--- a/tomato64/board/x86_64/overlay/sbin/upgrade
+++ b/tomato64/board/x86_64/overlay/sbin/upgrade
@@ -5,10 +5,15 @@ if [ $# -eq 0 ]; then
 	exit
 fi
 
-tar --touch -I "zstd -f" -xf $1 -C /
-
+mount -o remount,rw /
 result=$?
+if [ "$result" -ne 0 ]; then
+	printf 'error code "%d", unable to mount the filesystem as read/write' "$result"
+	exit
+fi
 
+tar --touch -I "zstd -f" -xf $1 -C /
+result=$?
 if [ "$result" -ne 0 ]; then
 	printf 'error code "%d" returned during extraction' "$result"
 	exit
