FT: others: mwwatchdog: refactoring, simplifying and shortening taking into account the specifics of sh in busybox
Update from FreshTomato
https://github.com/FreshTomato-Project/freshtomato-arm/commit/cc8bd00ea696c2bb9163ecb7a6be28f0172c749c

diff --git a/tomato64/package/others/others/mwwatchdog b/tomato64/package/others/others/mwwatchdog
--- a/tomato64/package/others/others/mwwatchdog
+++ b/tomato64/package/others/others/mwwatchdog
@@ -3,7 +3,8 @@ export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/root
 #
 # Copyright (C) 2015 shibby
 #
-# changes/fixes: 2018 - 2024 by pedro
+# changes/fixes: 2018 - 2025 by pedro
+# https://freshtomato.org/
 #
 
 
@@ -12,19 +13,20 @@ export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/root
 PID=$$
 PIDFILE="/var/run/mwwatchdog.pid"
 IPLISTFILE="/tmp/mwwatchdog.iplist"
-MWAN=$(NG mwan_num)
 IPLIST=""
+MWAN=$(NG mwan_num)
 MWANTABLE="wan"
+LOGI="logger -t mwwatchdog[$PID]"
+LOGE="logger -p ERROR -t mwwatchdog[$PID]"
+LOGW="logger -p WARN -t mwwatchdog[$PID]"
+LOGD=$([ "$(NG mwwatchdog_debug)" -gt 0 ] 2>/dev/null && echo "logger -p DEBUG -t mwwatchdog[$PID]" || echo "echo")
+
 
 i=1
 while [ $i -le $MWAN ]; do
 	[ "$i" -gt 1 ] && MWANTABLE="$MWANTABLE wan$i"
 	i=$((i+1))
 done
-
-LOGS="logger -t mwwatchdog[$PID]"
-[ "$(NG mwanwatchdog_debug)" -gt 0 ] 2>/dev/null && DEBUG="logger -p DEBUG -t mwwatchdog[$PID]" || DEBUG="echo"
-
 
 timeout() {
 	local cmd_pid sleep_pid retval
@@ -39,28 +41,36 @@ timeout() {
 }
 
 findHost() {
-	local host ip
-	local dst=$(NG mwan_ckdst)
-	local hostlist=$(echo $dst | sed 's/,/ /')
+	local host ip dst hostlist
+	dst=$(NG mwan_ckdst)
+	hostlist=$(echo "$dst" | sed 's/,/ /g')
 
+	IPLIST=""
 	for host in $hostlist; do
-		echo $host | grep -Eo '((([a-zA-Z]{1,2})|([0-9]{1,2})|([a-zA-Z0-9]{1,2})|([a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]))\.)+[a-zA-Z]{2,6}' && {
-			ip=$(nslookup $host 2>/dev/null | tail +5 | grep -v :: | awk '{print $3}' | tail -1)
+		if echo "$host" | grep -Eo '((([a-zA-Z]{1,2})|([0-9]{1,2})|([a-zA-Z0-9]{1,2})|([a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]))\.)+[a-zA-Z]{2,6}' >/dev/null 2>&1; then
+			# resolve domain name
+			ip=$(nslookup "$host" 2>/dev/null | tail -n +5 | grep -v '::' | awk '{print $3}' | tail -1)
 			IPLIST="${IPLIST} $ip"
-		} || IPLIST="${IPLIST} $host"
+		else
+			# treat as IP address
+			IPLIST="${IPLIST} $host"
+		fi
 	done
 
-	echo "$IPLIST" > $IPLISTFILE # because we're in subshell
+	# write result because we're in subshell
+	echo "$IPLIST" > "$IPLISTFILE"
 }
 
 dhcpFix() {
-	dhcpc-release $PREFIX
+	dhcpc-release "$1"
 	sleep 1
-	dhcpc-renew $PREFIX
+	dhcpc-renew "$1"
 }
 
 ifconfigChk() {
-	[ $(ifconfig $IFACE 2>/dev/null | grep inet | grep -Eo '((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' | grep -v '0.0.0.0' | wc -l) -eq 0 ] && ret_ifchk=0 || ret_ifchk=1
+	# check if interface has valid IP address
+	ret_ifchk=$(ifconfig "$IFACE" 2>/dev/null | grep inet | grep -Eo '((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' | grep -v '0.0.0.0' | wc -l)
+	[ "$ret_ifchk" -eq 0 ] && ret_ifchk=0 || ret_ifchk=1
 }
 
 mwwatchdogRun() {
@@ -73,32 +83,32 @@ mwwatchdogRun() {
 		DEMAND=$(NG "$PREFIX"_ppp_demand)
 		RESULT=0
 		PREFIX_MWAN=$PREFIX
-		PREFIX_LOG="WAN"$(echo $PREFIX"0" | cut -c 4- | tr '[234]' '[123]' | cut -c -1)
-		STATE_FILE="/var/lib/misc/"$PREFIX"_state"
+		PREFIX_LOG="WAN$(echo "$PREFIX"0 | cut -c 4- | tr '234' '123' | cut -c 1)"
+		STATE_FILE="/var/lib/misc/${PREFIX}_state"
 		local ret_ifchk
 
 		[ "$(NG "$PREFIX"_ck_pause)" -eq 1 ] && {
-			$DEBUG "MWWatchdog paused for $PREFIX_LOG - skipping ..."
+			$LOGD "MWWatchdog paused for $PREFIX_LOG - skipping ..."
 			continue
 		}
 
 		[ "$PROTO" != "disabled" ] && {
 			[ "$(NG mwan_debug)" -gt 0 ] && {
 				ISUP=$(wanuptime "$PREFIX")
-				ISGW=$(ip route | grep $IFACE | grep -v link | wc -l)
-				$DEBUG "prefix=$PREFIX_LOG, iface=$IFACE, uptime=$ISUP, ISGW=$ISGW, WEIGHT=$WEIGHT"
+				ISGW=$(ip route | grep "$IFACE" | grep -v link | wc -l)
+				$LOGD "prefix=$PREFIX_LOG, iface=$IFACE, uptime=$ISUP, ISGW=$ISGW, WEIGHT=$WEIGHT"
 			}
 
-			[ "$PROTO" == "dhcp" ] && {
+			[ "$PROTO" = "dhcp" ] && {
 				ifconfigChk
-				[ "$ret_ifchk" -eq 0 ] && { dhcpFix $PREFIX; sleep 3; }
+				[ "$ret_ifchk" -eq 0 ] && dhcpFix "$PREFIX" && sleep 3
 			}
 
 			[ "$PROTO" != "lte" ] && {
 				ifconfigChk
 				[ "$ret_ifchk" -eq 0 ] && {
-					$DEBUG "$PREFIX doesn't have an IP address. Skipping..."
-					echo "0" > $STATE_FILE
+					$LOGD "$PREFIX doesn't have an IP address. Skipping..."
+					echo "0" > "$STATE_FILE"
 					continue
 				}
 			}
@@ -106,126 +116,118 @@ mwwatchdogRun() {
 			DEFAULT_ROUTE_FRAGMENT=$(ip route | grep default | cut -d' ' -f2-)
 			GATEWAY_FRAGMENT="via $(NG "$PREFIX"_gateway)"
 			[ "$ISPPPD" -eq 1 ] && GATEWAY_FRAGMENT=""
+
+			# add routes
 			for IP in $IPLIST; do
-				[ ! -z "$DEFAULT_ROUTE_FRAGMENT" ] && {
-					ROUTE_EXEC="ip route add $IP $DEFAULT_ROUTE_FRAGMENT"
-					$DEBUG $ROUTE_EXEC
-					$ROUTE_EXEC &>/dev/null
+				[ -n "$DEFAULT_ROUTE_FRAGMENT" ] && {
+					$LOGD ip route add "$IP" $DEFAULT_ROUTE_FRAGMENT
+					ip route add "$IP" $DEFAULT_ROUTE_FRAGMENT 2>/dev/null
 				}
-				ROUTE_EXEC="ip route add $IP dev $IFACE $GATEWAY_FRAGMENT metric 50000"
-				$DEBUG $ROUTE_EXEC
-				$ROUTE_EXEC &>/dev/null
+				$LOGD ip route add "$IP" dev "$IFACE" $GATEWAY_FRAGMENT metric 50000
+				ip route add "$IP" dev "$IFACE" $GATEWAY_FRAGMENT metric 50000 2>/dev/null
 			done
 
-			$DEBUG "start test for: $IFACE ..."
-			if [ "$METHOD" -eq 1 ]; then
-				ckping
-			elif [ "$METHOD" -eq 2 ]; then
-				cktracert
+			$LOGD "start test for: $IFACE ..."
+			case "$METHOD" in
+				1) ckping ;;
+				2) cktracert ;;
 # BBT-BEGIN
-			else
-				ckcurl
+				*) ckcurl ;;
 # BBT-END
-			fi
+			esac
 
+			# remove routes
 			for IP in $IPLIST; do
-				[ ! -z "$DEFAULT_ROUTE_FRAGMENT" ] && {
-					ROUTE_EXEC="ip route del $IP $DEFAULT_ROUTE_FRAGMENT"
-					$DEBUG $ROUTE_EXEC
-					$ROUTE_EXEC &>/dev/null
+				[ -n "$DEFAULT_ROUTE_FRAGMENT" ] && {
+					$LOGD ip route del "$IP" $DEFAULT_ROUTE_FRAGMENT
+					ip route del "$IP" $DEFAULT_ROUTE_FRAGMENT 2>/dev/null
 				}
-				ROUTE_EXEC="ip route del $IP dev $IFACE $GATEWAY_FRAGMENT metric 50000"
-				$DEBUG $ROUTE_EXEC
-				$ROUTE_EXEC &>/dev/null
+				$LOGD ip route del "$IP" dev "$IFACE" $GATEWAY_FRAGMENT metric 50000
+				ip route del "$IP" dev "$IFACE" $GATEWAY_FRAGMENT metric 50000 2>/dev/null
 			done
 
-			# wan is down
-			[ "$RESULT" -eq 0 ] && {
-				[ "$PROTO" == "lte" ] && {
-					$LOGS "Connection $PREFIX_LOG DOWN - Reconnecting ..."
-					echo "0" > $STATE_FILE
-					switch4g $PREFIX
+			# handle WAN down
+			if [ "$RESULT" -eq 0 ]; then
+				[ "$PROTO" = "lte" ] && {
+					$LOGI "Connection $PREFIX_LOG DOWN - Reconnecting ..."
+					echo "0" > "$STATE_FILE"
+					switch4g "$PREFIX"
 				} || {
-					[ "$PREFIX" == "wan" -a "$MWAN" -gt 1 ] && PREFIX_MWAN="wan1" # "wan" means restart all WANs, but we only want restart one
+					[ "$PREFIX" = "wan" ] && [ "$MWAN" -gt 1 ] && PREFIX_MWAN="wan1" # "wan" means restart all WANs, but we only want restart one
 
-					[ "$(NG action_service)" == "wan-restart" -o "$(NG action_service)" == $PREFIX_MWAN"-restart" -o "$(NG action_service)" == "wan-restart-c" -o "$(NG action_service)" == $PREFIX_MWAN"-restart-c" ] && {
-						$LOGS "Connection $PREFIX_LOG DOWN - Reconnect is already in progress ..."
-					} || {
-						echo "0" > $STATE_FILE
+					if [ "$(NG action_service)" = "wan-restart" ] || [ "$(NG action_service)" = "$PREFIX_MWAN-restart" ] || [ "$(NG action_service)" = "wan-restart-c" ] || [ "$(NG action_service)" = "$PREFIX_MWAN-restart-c" ]; then
+						$LOGI "Connection $PREFIX_LOG DOWN - Reconnect is already in progress ..."
+					else
+						echo "0" > "$STATE_FILE"
 
-						if [ "$PROTO" == "pppoe" -o "$PROTO" == "pptp" -o "$PROTO" == "l2tp" -o "$PROTO" == "ppp3g" ] && [ "$DEMAND" -eq 1 -a "$ISPPPD" -eq 0 ]; then
-							$LOGS "Killing orphaned connect-on-demand listen process ..."
-							LISTEN_PID=$(ps | grep [l]isten | grep $PREFIX | awk '{print $1}' | head -n1)
-							[ -n $LISTEN_PID ] && {
-								kill -9 $LISTEN_PID
-								$LOGS "Killed $LISTEN_PID"
-							} || {
-								$LOGS "Connect-on-demand listen not running"
-							}
+						if ([ "$PROTO" = "pppoe" ] || [ "$PROTO" = "pptp" ] || [ "$PROTO" = "l2tp" ] || [ "$PROTO" = "ppp3g" ]) && [ "$DEMAND" -eq 1 ] && [ "$ISPPPD" -eq 0 ]; then
+							$LOGI "Killing orphaned connect-on-demand listen process ..."
+							LISTEN_PID=$(ps | grep '[l]isten' | grep "$PREFIX" | awk '{print $1}' | head -1)
+							if [ -n "$LISTEN_PID" ]; then
+								kill -9 "$LISTEN_PID" 2>/dev/null
+								$LOGI "Killed $LISTEN_PID"
+							else
+								$LOGI "Connect-on-demand listen not running"
+							fi
 
-							$LOGS "Connection $PREFIX_LOG DOWN - Reconnecting ..."
-							service $PREFIX_MWAN restart
+							$LOGI "Connection $PREFIX_LOG DOWN - Reconnecting ..."
+							service "$PREFIX_MWAN" restart
 						else
-							$LOGS "Connection $PREFIX_LOG DOWN - Reconnect will be handled by another process ..."
+							$LOGI "Connection $PREFIX_LOG DOWN - Reconnect will be handled by another process ..."
 						fi
-					}
+					fi
 				}
-			} || {
-				[ "$PROTO" == "dhcp" -a "$(cat $STATE_FILE 2>/dev/null || echo 1 )" -eq 0 ] && { # connected + DHCP + previous status - disconnected? release/renew
-					dhcpFix
-				}
-				$DEBUG "Connection $PREFIX_LOG is functioning"
-				echo "1" > $STATE_FILE
-			}
+			else
+				# handle WAN up
+				[ "$PROTO" = "dhcp" ] && [ "$(cat "$STATE_FILE" 2>/dev/null || echo 1)" -eq 0 ] && dhcpFix "$PREFIX" # connected + DHCP + previous status - disconnected? release/renew
+				$LOGD "Connection $PREFIX_LOG is functioning"
+				echo "1" > "$STATE_FILE"
+			fi
 		}
 	done
 }
 
 cktracert() {
 	local RXBYTES1 RXBYTES2 IP
-	local RXBYTES_MIN_DIFF=$(NG mwan_diff) # declare the minimum number of bytes indicating a working WAN
+	# minimum bytes indicating working WAN
+	local RXBYTES_MIN_DIFF=$(NG mwan_diff)
 
 	for IP in $IPLIST; do
 		RXBYTES1=$(cat /sys/class/net/$IFACE/statistics/rx_bytes 2>/dev/null)
-		# we need only send/receive few packages to be sure if connection works
-		traceroute -i $IFACE -n -w 1 -m 10 -q 1 -z 1 $IP &>/dev/null
+		traceroute -i "$IFACE" -n -w 1 -m 10 -q 1 -z 1 "$IP" 2>/dev/null
 		sleep 1
 		RXBYTES2=$(cat /sys/class/net/$IFACE/statistics/rx_bytes 2>/dev/null)
-		[ "$RXBYTES2" -gt "$(($RXBYTES1 + $RXBYTES_MIN_DIFF))" ] && { RESULT=1; break; }
+		[ "$RXBYTES2" -gt $((RXBYTES1 + RXBYTES_MIN_DIFF)) ] && { RESULT=1; break; }
 	done
 
-	[ "$RESULT" -gt 0 ] && $DEBUG "tracert test result for: $IFACE - OK" || $DEBUG "tracert test result for: $IFACE - FAILED!"
+	[ "$RESULT" -gt 0 ] && $LOGD "tracert test result for: $IFACE - OK" || $LOGD "tracert test result for: $IFACE - FAILED!"
 }
 
 ckping() {
-	local IP
-	local i=0
+	local IP i=0
 
 	for IP in $IPLIST; do
 		i=$((i+1))
-		# "0" means 100% loss - not receive any package
-		ping -c $((i+1)) -A -W $((i+2)) -q -I $IFACE $IP >/dev/null && RESULT=$((RESULT+1))
-
+		# 0 means 100% loss - no packages received
+		ping -c $((i+1)) -A -W $((i+2)) -q -I "$IFACE" "$IP" >/dev/null 2>&1 && RESULT=$((RESULT+1))
 		[ "$RESULT" -gt 0 ] && break
 	done
 
-	[ "$RESULT" -gt 0 ] && $DEBUG "ping test result for: $IFACE - OK" || $DEBUG "ping test result for: $IFACE - FAILED!"
+	[ "$RESULT" -gt 0 ] && $LOGD "ping test result for: $IFACE - OK" || $LOGD "ping test result for: $IFACE - FAILED!"
 }
 
 # BBT-BEGIN
 ckcurl() {
-	local IP
-	local i=0
+	local IP i=0
 
 	for IP in $IPLIST; do
 		i=$((i+1))
-		curl $IP --interface $IFACE --connect-timeout $((i+3)) -ksfI -o /dev/null && RESULT=$((RESULT+1))
+		curl "$IP" --interface "$IFACE" --connect-timeout $((i+3)) -ksfI -o /dev/null 2>/dev/null && RESULT=$((RESULT+1))
 		[ "$RESULT" -gt 0 ] && break
-
 		sleep $i
 	done
 
-	[ "$RESULT" -gt 0 ] && $DEBUG "curl test result for: $IFACE - OK" || $DEBUG "curl test result for: $IFACE - FAILED!"
+	[ "$RESULT" -gt 0 ] && $LOGD "curl test result for: $IFACE - OK" || $LOGD "curl test result for: $IFACE - FAILED!"
 }
 # BBT-END
 
@@ -233,24 +235,22 @@ mwwatchdogAdd() {
 	local CKTIME=$(NG mwan_cktime)
 	local MINS=$((CKTIME/60))
 
-	[ "$MINS" -gt 0 ] && {
-		cru l | grep mwwatchdogJob >/dev/null || cru a mwwatchdogJob "*/$MINS * * * * /usr/sbin/mwwatchdog"
-	}
+	[ "$MINS" -gt 0 ] && cru l | grep -q mwwatchdogJob || cru a mwwatchdogJob "*/$MINS * * * * /usr/sbin/mwwatchdog"
 }
 
 mwwatchdogDel() {
-	cru l | grep mwwatchdogJob >/dev/null && cru d mwwatchdogJob
+	cru l | grep -q mwwatchdogJob && cru d mwwatchdogJob
 }
 
 mwanJob() {
-	cru l | grep mwanJob >/dev/null && cru d mwanJob || cru a mwanJob "*/1 * * * * /usr/sbin/mwwatchdog alive"
+	cru l | grep -q mwanJob && cru d mwanJob || cru a mwanJob "*/1 * * * * /usr/sbin/mwwatchdog alive"
 }
 
 mwanAlive() {
 	[ "$MWAN" -gt 1 ] && {
-		ps | grep -q [m]wanroute && $DEBUG "mwanroute is running" || {
-			$LOGS "mwanroute not found, I'll try to recover it"
-			nohup mwanroute &
+		ps | grep -q '[m]wanroute' && $LOGD "mwanroute is running" || {
+			$LOGW "mwanroute not found, trying to recover it"
+			nohup mwanroute >/dev/null 2>&1 &
 		}
 	}
 }
@@ -258,27 +258,17 @@ mwanAlive() {
 checkPid() {
 	local PIDNO
 
-	[ -f $PIDFILE ] && {
-		PIDNO=$(cat $PIDFILE)
-		cat "/proc/$PIDNO/cmdline" &>/dev/null
+	if [ -f "$PIDFILE" ]; then
+		PIDNO=$(cat "$PIDFILE")
+		if kill -0 "$PIDNO" 2>/dev/null; then
+			$LOGW "another process in action - exiting ..."
+			exit 0
+		fi
+	fi
 
-		[ $? -eq 0 ] && {
-			$LOGS "Another process in action - Exiting ..."
-			exit 0
-		} || {
-			# Process not found assume not running
-			echo $PID > $PIDFILE
-			[ $? -ne 0 ] && {
-				$LOGS "Could not create PID file"
-				exit 0
-			}
-		}
-	} || {
-		echo $PID > $PIDFILE
-		[ $? -ne 0 ] && {
-			$LOGS "Could not create PID file"
-			exit 0
-		}
+	echo $PID > $PIDFILE || {
+		$LOGE "could not create PID file"
+		exit 0
 	}
 }
 
@@ -286,27 +276,27 @@ checkPidSwitch() {
 	local SPREFIX
 
 	for SPREFIX in $MWANTABLE; do
-		[ -f /var/run/switch3g_$SPREFIX.pid ] && {
-			[ "$(ps | grep [s]witch3g | wc -l)" -eq 0 ] && {
-				# pid file exists but process doesn't
-				rm /var/run/switch3g_$SPREFIX.pid
-			} || {
-				$LOGS "Switch3g ($SPREFIX) script in action - Exiting ..."
-				rm -f $PIDFILE &>/dev/null
+		if [ -f "/var/run/switch3g_$SPREFIX.pid" ]; then
+			if ! ps | grep -q '[s]witch3g'; then
+				# PID file exists but process doesn't
+				rm "/var/run/switch3g_$SPREFIX.pid" 2>/dev/null
+			else
+				$LOGW "switch3g ($SPREFIX) script in action - exiting ..."
+				rm -f "$PIDFILE" 2>/dev/null
 				exit 0
-			}
-		}
+			fi
+		fi
 
-		[ -f /var/run/switch4g_$SPREFIX.pid ] && {
-			[ "$(ps | grep [s]witch4g | wc -l)" -eq 0 ] && {
-				# pid file exists but process doesn't
-				rm /var/run/switch4g_$SPREFIX.pid
-			} || {
-				$LOGS "Switch4g ($SPREFIX) script in action - Exiting ..."
-				rm -f $PIDFILE &>/dev/null
+		if [ -f "/var/run/switch4g_$SPREFIX.pid" ]; then
+			if ! ps | grep -q '[s]witch4g'; then
+				# PID file exists but process doesn't
+				rm "/var/run/switch4g_$SPREFIX.pid" 2>/dev/null
+			else
+				$LOGW "switch4g ($SPREFIX) script in action - exiting ..."
+				rm -f "$PIDFILE" 2>/dev/null
 				exit 0
-			}
-		}
+			fi
+		fi
 	done
 }
 
@@ -314,38 +304,43 @@ checkPidSwitch() {
 ###################################################
 
 
-if [ "$1" == "add" ]; then
-	mwwatchdogAdd
-	mwanJob
-elif [ "$1" == "del" ]; then
-	mwwatchdogDel
-elif [ "$1" == "alive" ]; then
-	mwanAlive
-elif [ "$(NG g_upgrade)" != "1" -a "$(NG g_reboot)" != "1" ]; then
-	checkPid
+case "$1" in
+	add)
+		mwwatchdogAdd
+		mwanJob
+		;;
+	del)
+		mwwatchdogDel
+		;;
+	alive)
+		mwanAlive
+		;;
+	*)
+		if [ "$(NG g_upgrade)" != "1" ] && [ "$(NG g_reboot)" != "1" ]; then
+			checkPid
+			checkPidSwitch
+			mwanJob
 
-	checkPidSwitch
+			# run with a 10 sec timeout to not hang
+			timeout 10 findHost
+			[ -f "$IPLISTFILE" ] && IPLIST=$(cat "$IPLISTFILE")
+			[ -z "$IPLIST" ] && IPLIST="8.8.8.8" # Resilient IP if the list is empty
 
-	mwanJob
+			# filter out DNS IPs from the list
+			BADIPLIST=""
+			for IP in $IPLIST; do
+				nvram show 2>/dev/null | grep -E '^wan.?_dns=' | cut -f2 -d= | tr '\n' ' ' | grep -Fq "$IP" && BADIPLIST="${BADIPLIST} $IP"
+			done
 
-	# run with a 10 sec timeout to not hang
-	timeout 10 findHost
-	[ -f $IPLISTFILE ] && IPLIST=$(cat $IPLISTFILE)
-	[ -z "$IPLIST" ] && IPLIST="8.8.8.8" # resilient IP if the list is empty
+			# remove bad IPs from IPLIST
+			if [ -n "$BADIPLIST" ]; then
+				IPLIST=$(echo "$IPLIST" | tr ' ' '\n' | grep -vFf <(echo "$BADIPLIST" | tr ' ' '\n') | tr '\n' ' ' | sed 's/ $//')
+			fi
 
-	for IP in $IPLIST; do
-		for dns in $(nvram show 2>/dev/null | grep -E ^wan.?_dns= | cut -f2 -d= | tr "\n" " " | grep -Ev ^$); do
-			[ $dns == $IP ] && BADIPLIST="${BADIPLIST} $IP"
-		done
-	done
-	[[ ! -v ${BADIPLIST} ]] && {
-		IIPLIST=$(echo $IPLIST | tr " " "\n" | for i in $BADIPLIST; do grep -v $i; done | tr "\n" " " | tr -s ' ')
-		IPLIST=$IIPLIST
-	}
+			mwwatchdogRun
+			[ -f "$IPLISTFILE" ] && rm "$IPLISTFILE"
+		fi
+		;;
+esac
 
-	mwwatchdogRun
-
-	[ -f $IPLISTFILE ] && rm $IPLISTFILE
-fi
-
-rm -f $PIDFILE &>/dev/null
+rm -f "$PIDFILE" 2>/dev/null
