Add support for the Banana Pi BPI-R3
Creates images for sdcard and internal emmc

diff --git a/tomato64/package/tomato64-helper-scripts/sbin/upgrade b/tomato64/package/tomato64-helper-scripts/sbin/upgrade
--- a/tomato64/package/tomato64-helper-scripts/sbin/upgrade
+++ b/tomato64/package/tomato64-helper-scripts/sbin/upgrade
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+. /usr/sbin/nvram_ops
+
 if [ $# -eq 0 ]; then
 	echo "missing .tzst file argument"
 	exit
@@ -20,7 +22,7 @@ if [ "$result" -ne 0 ]; then
 fi
 
 # x86_64
-if [ -f /boot/bzImage ]; then
+if [ -f /boot/bzImage ] && [ "$(NG "t_model_name")" == "x86_64" ]; then
 	kernel=`file -bL /boot/bzImage  | sed 's/.*version //;s/ .*//'`
 	for dir in /lib/modules/*; do
 		[ "$dir" = "/lib/modules/$kernel" ] && continue
@@ -30,7 +32,7 @@ if [ -f /boot/bzImage ]; then
 fi
 
 # GL-MT6000
-if [ -f /boot/glinet_gl-mt6000-kernel.bin ]; then
+if [ -f /boot/glinet_gl-mt6000-kernel.bin ] && [ "$(NG "t_model_name")" == "GL.iNet GL-MT6000" ]; then
 
 	export EMMC_KERNEL_BLOCKS=$(($(dd if=/boot/glinet_gl-mt6000-kernel.bin of=/dev/mmcblk0p6 bs=512 2>&1 | grep "records out" | cut -d' ' -f1)))
 
@@ -56,8 +58,35 @@ if [ -f /boot/glinet_gl-mt6000-kernel.bin ]; then
 	printf "image successfully flashed\n"
 fi
 
+# BPI-R3
+if [ -f /boot/tomato64-bananapi_bpi-r3-sysupgrade.itb ] && [ "$(NG "t_model_name")" == "Banana Pi BPI-R3" ]; then
+
+	export EMMC_KERNEL_BLOCKS=$(($(dd if=/boot/tomato64-bananapi_bpi-r3-sysupgrade.itb of=/dev/mmcblk0p5 bs=512 2>&1 | grep "records out" | cut -d' ' -f1)))
+
+	result=$?
+	if [ "$result" -ne 0 ]; then
+		printf 'error code "%d" returned during kernel write' "$result"
+		exit
+	fi
+
+	dd if=/dev/zero of=/dev/mmcblk0p5 bs=512 seek=$EMMC_KERNEL_BLOCKS count=8 >/dev/null 2>&1
+
+	result=$?
+	if [ "$result" -ne 0 ]; then
+		printf 'error code "%d" returned during kernel padding write' "$result"
+		exit
+	fi
+
+	kernel=$(strings /boot/tomato64-bananapi_bpi-r3-sysupgrade.itb | grep -i "Linux-" | awk '{print $3}' | sed "s/.*-//")
+	for dir in /lib/modules/*; do
+		[ "$dir" = "/lib/modules/$kernel" ] && continue
+		rm -rf "$dir"
+	done
+	printf "image successfully flashed\n"
+fi
+
 # BPI-R3 Mini
-if [ -f /boot/tomato64-bpi-r3-mini-sysupgrade.itb ]; then
+if [ -f /boot/tomato64-bpi-r3-mini-sysupgrade.itb ] && [ "$(NG "t_model_name")" == "Banana Pi BPI-R3 Mini" ]; then
 
 	export EMMC_KERNEL_BLOCKS=$(($(dd if=/boot/tomato64-bpi-r3-mini-sysupgrade.itb of=/dev/mmcblk0p4 bs=512 2>&1 | grep "records out" | cut -d' ' -f1)))
 
