Add support for Flint 4
Hardware
--------
MediaTek Quad-Core Cortex-A73 @ 1.8GHz
2GB DDR4 RAM
64GB eMMC on board
1x 10G WAN/LAN Ethernet
1x 10G SFP+ WAN/LAN
1x 2.5G WAN/LAN Ethernet
3x 2.5G LAN Ethernet
4x 1G LAN Ethernet
Wi-Fi 7 (802.11a/b/g/n/ac/ax/be): 688 Mbps (2.4GHz) / 4323 Mbps (5GHz) / 8646 Mbps (6GHz)
6x Foldable external Wi-Fi antennas
2x Buttons (Power, Reset)
1x USB 3.0 Port (Type-A)
1x USB 3.0 Port (Type-C)
12V/4A DC Power

diff --git a/tomato64/package/tomato64-helper-scripts/sbin/upgrade b/tomato64/package/tomato64-helper-scripts/sbin/upgrade
--- a/tomato64/package/tomato64-helper-scripts/sbin/upgrade
+++ b/tomato64/package/tomato64-helper-scripts/sbin/upgrade
@@ -94,6 +94,28 @@ if [ -f /boot/glinet_gl-mt6000-kernel.bin ] && [ "$(NG "t_model_name")" == "GL.i
 	printf "image successfully flashed\n"
 fi
 
+# GL-BE14000
+if [ -f /boot/glinet_gl-be14000-kernel.bin ] && [ "$(NG "t_model_name")" == "GL.iNet GL-BE14000" ]; then
+
+	export EMMC_KERNEL_BLOCKS=$(($(dd if=/boot/glinet_gl-be14000-kernel.bin of=/dev/mmcblk0p6 bs=512 2>&1 | grep "records out" | cut -d' ' -f1)))
+
+	result=$?
+	if [ "$result" -ne 0 ]; then
+		printf 'error code "%d" returned during kernel write' "$result"
+		exit
+	fi
+
+	dd if=/dev/zero of=/dev/mmcblk0p6 bs=512 seek=$EMMC_KERNEL_BLOCKS count=8 >/dev/null 2>&1
+
+	result=$?
+	if [ "$result" -ne 0 ]; then
+		printf 'error code "%d" returned during kernel padding write' "$result"
+		exit
+	fi
+
+	printf "image successfully flashed\n"
+fi
+
 # BPI-R3
 if [ -f /boot/tomato64-bananapi_bpi-r3-sysupgrade.itb ] && [ "$(NG "t_model_name")" == "Banana Pi BPI-R3" ]; then
 
